### PR TITLE
Add BassFace

### PR DESCRIPTION
**Pull request by unionthugface**
Adding bassface.dance

### CODE REVIEW

**Comment by abdonrd** [comment]
Hi @unionthugface! Thanks for the PR!

I tried the web, but it doesn't seem to work. 😕

**Comment by unionthugface** [comment]
It's just a splash screen for now! In the middle of development for another project.

. . . is there no splash screen? :(

**Comment by abdonrd** [comment]
Ok! Then we can wait for the project to develop a little more.

**Comment by Link2Twenty** [comment]
This is actually a site now. Also, I see it's using one of my elements 😉

**Comment by abdonrd** [comment]
Thanks! 👏

**Pull request merged**
