### PR TITLE
Remove Contactlab projects/applications

### PR DESCRIPTION
**Pull request by StefanoMagrassi**

### CODE REVIEW

**Comment by abdonrd** [comment]
@StefanoMagrassi oh! You no longer use Polymer?

**Comment by StefanoMagrassi** [comment]
@abdonrd we're changing our frontend architecture (and I'm cleaning up our organization's repositories list)  😃

**Comment by abdonrd** [comment]
@StefanoMagrassi could you comment what frontend architecture you are going to do? 😄

**Comment by StefanoMagrassi** [comment]
@abdonrd we still are in a "evaluation phase" 😴 

> You know, a lotta ins, lotta outs

Almost certainly not *polymer-based*, probably something with Typescript, RxJs and a view library (React, Preact, Inferno or similar)

**Comment by abdonrd** [comment]
@StefanoMagrassi ouch! What is the reason for leaving Web Components?

Thanks for the answer!

**Pull request merged**
